apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: gbot
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjM1JoY3pjeU56cG5hSEJmY2xWamVqa3pZVEpZVURKdGFFaFdOamhOWTFCVlNIRkJUR28wV1haaU1YWm9jbXBuIn19fQ==