# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: stas727
  arch: amd64
  os: "linux"
  registry: "ghcr.io"
  tag: "v1.0.0-b1e59d6-linux-amd64"
secret:
  name: "gbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
