# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: stas727
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "-"
  arch: amd64
  os: ""
  registry: ""
secret:
  secretName: gbot
  tokenKey: token
  tokenName: TELE_TOKEN
